---
addons:
- name: bpm
  jobs:
  - name: bpm
    release: bpm

instance_groups:
- name: zookeeper
  azs: [z1, z2, z3]
  instances: ((zookeeper_instances))
  jobs:
  - name: zookeeper
    release: zookeeper
    properties: {}
  - name: status
    release: zookeeper
  vm_type: ((zookeeper_vm_type))
  stemcell: ((zookeeper_stemcell))
  persistent_disk_type: ((zookeeper_persistent_disk_type))
  networks: [{name: ((zookeeper_network))}]
- name: smoke-tests
  lifecycle: errand
  azs: [z1, z2, z3]
  instances: 1
  vm_type: ((smoke_tests_vm_type))
  stemcell: ((smoke_tests_stemcell))
  networks: [{name: ((smoke_tests_network))}]
  jobs:
  - name: smoke-tests
    release: zookeeper
- name: kafka
  azs: [z1, z2, z3]
  instances: ((kafka_instances))
  vm_type: ((kafka_vm_type))
  stemcell: ((kafka_stemcell))
  persistent_disk_type: ((kafka_persistent_disk_type))
  networks: [{name: ((kafka_network))}]
  jobs:
  - name: kafka
    release: kafka
    # provides:
    #   kafka-address:
    #     as: the-kafka-address
    # custom_provider_definitions:
    # - name: kafka-address
    #   type: address
    properties: {}
- name: sanitytest
  lifecycle: errand
  azs: [z1, z2, z3]
  instances: 1
  vm_type: ((sanitytest_vm_type))
  stemcell: ((sanitytest_stemcell))
  networks: [{name: ((sanitytest_network))}]
  jobs:
  - name: sanitytest
    release: kafka
- name: generatetopics
  lifecycle: errand
  azs: [z1, z2, z3]
  instances: 1
  vm_type: ((generatetopics_vm_type))
  stemcell: ((generatetopics_stemcell))
  networks: [{name: ((generatetopics_network))}]
  jobs:
  - name: generatetopics
    release: kafka
- name: cmak
  azs: [z1, z2, z3]
  instances: ((cmak_instances))
  jobs:
  - name: cmak
    release: cmak
    properties:
      password: ((cmak_password))
  vm_type: ((cmak_vm_type))
  stemcell: ((cmak_stemcell))
  persistent_disk_type: ((cmak_persistent_disk_type))
  networks: [{name: ((cmak_network))}]

name: ((deployment_name))

releases:
- name: bpm
  sha1: ((bpm_sha1))
  version: ((bpm_version))
- name: zookeeper
  sha1: ((zookeeper_sha1))
  version: ((zookeeper_version))
- name: kafka
  sha1: ((kafka_sha1))
  version: ((kafka_version))
- name: cmak
  sha1: ((cmak_sha1))
  version: ((cmak_version))

stemcells:
- alias: default
  os: ((kafka_deployment_stemcell_os))
  version: ((kafka_deployment_stemcell_version))

update:
  canaries: 1
  canary_watch_time: 1000-60000
  update_watch_time: 1000-60000
  max_in_flight: 1
  serial: true

variables:
- name: cmak_password
  type: password
# - name: kafka_ca
#   type: certificate
#   options:
#     is_ca: true
#     common_name: ((deployment_name))
# - name: kafka_tls_certificate
#   type: certificate
#   options:
#     ca: kafka_ca
#     common_name: ((deployment_name))_server
#   consumes:
#     alternative_name: the-kafka-address