---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: paymentshubrebels/bosh-utils
    tag: 'latest'

inputs:
- name: kafka-compiled-release
- name: zookeeper-compiled-release
- name: cmak-compiled-release
- name: bpm-compiled-release
- name: ubuntu-xenial
- name: kafka-deployment
- name: kafka-sha1
- name: zookeeper-sha1
- name: cmak-sha1
- name: bpm-sha1
- name: bumped-version
- name: running-version

outputs:
  - name: target
params:
  deployment_name:
  BOSH_ENVIRONMENT:
  BOSH_CA_CERT:
  BOSH_CLIENT:
  BOSH_CLIENT_SECRET:
run:
  path: ./create_offline_release.sh